### ISSUE TITLE
Dashboard View

### ISSUE THREAD

**Issue by alvinmarshall** [Bik-KrlvnOrg/sms_client#13]
This feature should be dynamic and display different
menus for user roles

Different menus will be added later for all users

- [x] apply navigation to this view after authentication

# Layout

![03_Student](https://user-images.githubusercontent.com/21101827/88713056-3b1f3300-d10a-11ea-8c43-55d618285d34.jpg)

**Comment by alvinmarshall** [comment]
@apprince how many menus do you think the student app should have ?
the web files are not working again, so i came up this close look. it will be dynamic
depending on the user role:
* Admin
* Staff
* Student

All the authentications are done, you can download file from the actions menu, select one of the pass build, download artifact

**Comment by apprince** [comment]
@Bik-Krlvn  Ok, I think that is ok, Basing it on the Role. Nice Job Done.
